import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  Briefcase,
  Calendar,
  CalendarClock,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Cloud,
  Code,
  Code2,
  Component,
  Cpu,
  Database,
  FileSearch,
  FileText,
  GitBranch,
  Globe,
  Grid3x3,
  Headphones,
  HelpCircle,
  Home,
  Image,
  Key,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Library,
  Lightbulb,
  Link,
  Lock,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Network,
  PackageCheck,
  Play,
  PlayCircle,
  PlugZap,
  Presentation,
  Radio,
  Rocket,
  Route,
  Scale,
  Search,
  Server,
  Share2,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  TrendingUp,
  Trophy,
  UserCircle,
  UserRound,
  Users,
  VectorSquare,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bar-chart': BarChart3,
  'book-open': BookOpen,
  Bot,
  Brain,
  'brain-circuit': BrainCircuit,
  Briefcase,
  Calendar,
  'calendar-clock': CalendarClock,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  Cloud,
  Code,
  'code-2': Code2,
  Component,
  Cpu,
  Database,
  'file-search': FileSearch,
  'file-text': FileText,
  'git-branch': GitBranch,
  Globe,
  'grid-3x3': Grid3x3,
  Headphones,
  'help-circle': HelpCircle,
  Home,
  Image,
  Key,
  Layers,
  Layout,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  Library,
  Lightbulb,
  Link,
  Lock,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Network,
  'package-check': PackageCheck,
  Play,
  'play-circle': PlayCircle,
  'plug-zap': PlugZap,
  Presentation,
  Radio,
  Rocket,
  Route,
  Scale,
  Search,
  Server,
  'share-2': Share2,
  Settings,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  'trending-up': TrendingUp,
  Trophy,
  'user-circle': UserCircle,
  'user-round': UserRound,
  Users,
  'vector-square': VectorSquare,
  Wand2,
  Wrench,
  Zap,
}

interface IconProps {
  name: string
  className?: string
  size?: number
}

export const Icon = ({ name, className, size = 20 }: IconProps) => {
  const LucideIcon = iconMap[name] || Lightbulb
  return <LucideIcon className={className} size={size} />
}
